language: cpp

matrix:
  include:
    - name: Linux GCC 6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - name: Linux Clang 5
      os: linux
      addons:
        apt:
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - name: Linux Clang 3.9
      os: linux
      addons:
        apt:
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - name: Mac Clang (Xcode 9)
      os: osx
      osx_image: xcode9
      
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cd build_cmake && ./build.sh
  - cd ..
  - LC_NUMERIC="C" ./build_cmake/FleeceTests
  - LC_NUMERIC="ru_RU.UTF-8" ./build_cmake/FleeceTests
